#!/usr/bin/env ruby

loop do
  $stdout.print '-> '
  line = $stdin.gets

  if line
    line.strip!
  else
    # in this case, EOF was received on $stdin
    exit
  end

  pid = fork {
    exec line
  }

  Process.wait pid
end

